
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace PatchDotNet.TUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class AnalyzeDialog : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label CurrentCount;
        
        private Terminal.Gui.Label label12;
        
        private Terminal.Gui.Label OptimizedCount;
        
        private void InitializeComponent() {
            this.OptimizedCount = new Terminal.Gui.Label();
            this.label12 = new Terminal.Gui.Label();
            this.CurrentCount = new Terminal.Gui.Label();
            this.label1 = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 3;
            this.label1.Y = 1;
            this.label1.Data = "label1";
            this.label1.Text = "Current records count:";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.CurrentCount.Width = 4;
            this.CurrentCount.Height = 1;
            this.CurrentCount.X = 37;
            this.CurrentCount.Y = 1;
            this.CurrentCount.Data = "CurrentCount";
            this.CurrentCount.Text = "0";
            this.CurrentCount.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.CurrentCount);
            this.label12.Width = 4;
            this.label12.Height = 1;
            this.label12.X = 3;
            this.label12.Y = 3;
            this.label12.Data = "label12";
            this.label12.Text = "Records count after optimize:";
            this.label12.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label12);
            this.OptimizedCount.Width = 4;
            this.OptimizedCount.Height = 1;
            this.OptimizedCount.X = 37;
            this.OptimizedCount.Y = 3;
            this.OptimizedCount.Data = "OptimizedCount";
            this.OptimizedCount.Text = "0";
            this.OptimizedCount.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.OptimizedCount);
        }
    }
}
