
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace PatchDotNet.TUI {
    using Terminal.Gui;
    
    
    public partial class AnalyzeDialog {
        public bool Canceled;
        Button ok = new("OK");
        Button cancel = new("Cancel");
        public AnalyzeDialog(long current,long after) {
            InitializeComponent();
            CurrentCount.Text= current.ToString();
            OptimizedCount.Text= after.ToString();
            X = Pos.Center();
            Y = Pos.Center();

            Width = Dim.Percent(85);
            Height = Dim.Percent(85);

            cancel.Clicked += () =>
            {
                Canceled = true;
                Application.RequestStop();
            };
            ok.Clicked += () => {
                Application.RequestStop();
            };
            AddButton(ok);
            AddButton(cancel);
        }
    }
}
