
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace PatchDotNet.TUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class CreatePatchDialog : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label13;
        
        private Terminal.Gui.Label ParentGuid;
        
        private Terminal.Gui.Label label1;

        public Terminal.Gui.TextField NewName;
        
        private Terminal.Gui.Label label12;
        
        public Terminal.Gui.TextField FilePath;
        
        private void InitializeComponent() {
            this.FilePath = new Terminal.Gui.TextField();
            this.label12 = new Terminal.Gui.Label();
            this.NewName = new Terminal.Gui.TextField();
            this.label1 = new Terminal.Gui.Label();
            this.ParentGuid = new Terminal.Gui.Label();
            this.label13 = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.label13.Width = 4;
            this.label13.Height = 1;
            this.label13.X = 3;
            this.label13.Y = 0;
            this.label13.Data = "label13";
            this.label13.Text = "Parent:";
            this.label13.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label13);
            this.ParentGuid.Width = 4;
            this.ParentGuid.Height = 1;
            this.ParentGuid.X = 12;
            this.ParentGuid.Y = 0;
            this.ParentGuid.Data = "ParentGuid";
            this.ParentGuid.Text = "parent-guid";
            this.ParentGuid.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.ParentGuid);
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 3;
            this.label1.Y = 2;
            this.label1.Data = "label1";
            this.label1.Text = "Name:";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.NewName.Width = 30;
            this.NewName.Height = 1;
            this.NewName.X = 12;
            this.NewName.Y = 2;
            this.NewName.Secret = false;
            this.NewName.Data = "NewName";
            this.NewName.Text = "";
            this.NewName.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.NewName);
            this.label12.Width = 4;
            this.label12.Height = 1;
            this.label12.X = 3;
            this.label12.Y = 4;
            this.label12.Data = "label12";
            this.label12.Text = "Path:";
            this.label12.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label12);
            this.FilePath.Width = 30;
            this.FilePath.Height = 1;
            this.FilePath.X = 12;
            this.FilePath.Y = 4;
            this.FilePath.Secret = false;
            this.FilePath.Data = "FilePath";
            this.FilePath.Text = "";
            this.FilePath.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.FilePath);
        }
    }
}
